from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable


class UIEvent(str, Enum):
    SCAN_STARTED = "SCAN_STARTED"
    SCAN_START_REQUESTED = "SCAN_START_REQUESTED"
    SCAN_STOP_REQUESTED = "SCAN_STOP_REQUESTED"
    SCAN_STOPPED = "SCAN_STOPPED"
    REVIEW_SESSION_READY = "REVIEW_SESSION_READY"
    TEST_CAPTURE_COMPLETE = "TEST_CAPTURE_COMPLETE"
    HOTKEY_REBOUND = "HOTKEY_REBOUND"
    FRAME_CAPTURED = "FRAME_CAPTURED"
    FRAME_ANALYZED = "FRAME_ANALYZED"
    BUFFER_PRESSURE_CHANGED = "BUFFER_PRESSURE_CHANGED"
    CONTINUITY_CHANGED = "CONTINUITY_CHANGED"
    OBSERVATION_CREATED = "OBSERVATION_CREATED"
    FIELD_RESOLVED = "FIELD_RESOLVED"
    FIELD_CONFLICTED = "FIELD_CONFLICTED"
    RECORD_CANDIDATE_CREATED = "RECORD_CANDIDATE_CREATED"
    RECORD_VERIFIED = "RECORD_VERIFIED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PROFILE_CHANGED = "PROFILE_CHANGED"
    CAPTURE_LOST = "CAPTURE_LOST"
    CAPTURE_RECOVERED = "CAPTURE_RECOVERED"
    SESSION_COMMITTED = "SESSION_COMMITTED"
    OVERLAY_RECORD_CLICK_RECEIVED = "OVERLAY_RECORD_CLICK_RECEIVED"
    OVERLAY_RECORD_CALLBACK_ENTERED = "OVERLAY_RECORD_CALLBACK_ENTERED"
    OVERLAY_EXTRACT_CLICK_RECEIVED = "OVERLAY_EXTRACT_CLICK_RECEIVED"
    RECORDER_START_REQUESTED = "RECORDER_START_REQUESTED"
    RECORDER_STARTED = "RECORDER_STARTED"
    RECORDER_START_FAILED = "RECORDER_START_FAILED"
    FIRST_FRAME_RECORDED = "FIRST_FRAME_RECORDED"
    RECORDING_FINALIZING = "RECORDING_FINALIZING"
    RECORDING_FINALIZED = "RECORDING_FINALIZED"
    RECORDING_FINALIZE_FAILED = "RECORDING_FINALIZE_FAILED"
    EXTRACTION_WORKER_START_REQUESTED = "EXTRACTION_WORKER_START_REQUESTED"
    EXTRACTION_WORKER_STARTED = "EXTRACTION_WORKER_STARTED"
    RECORDED_EXTRACTION_STARTED = "RECORDED_EXTRACTION_STARTED"
    RECORDED_EXTRACTION_PROGRESS = "RECORDED_EXTRACTION_PROGRESS"
    RECORDED_EXTRACTION_STALLED = "RECORDED_EXTRACTION_STALLED"
    RECORDED_EXTRACTION_COMPLETED = "RECORDED_EXTRACTION_COMPLETED"
    RECORDED_EXTRACTION_FAILED = "RECORDED_EXTRACTION_FAILED"
    REVIEW_SESSION_READY_PUBLISHED = "REVIEW_SESSION_READY_PUBLISHED"
    START_SCAN_MOUSE_ENTER = "START_SCAN_MOUSE_ENTER"
    START_SCAN_CLICK = "START_SCAN_CLICK"
    START_SCAN_CALLBACK_ENTERED = "START_SCAN_CALLBACK_ENTERED"
    START_RECORDING_MOUSE_ENTER = "START_RECORDING_MOUSE_ENTER"
    START_RECORDING_CLICK = "START_RECORDING_CLICK"
    START_RECORDING_CALLBACK_ENTERED = "START_RECORDING_CALLBACK_ENTERED"
    STOP_RECORDING_MOUSE_ENTER = "STOP_RECORDING_MOUSE_ENTER"
    STOP_RECORDING_CLICK = "STOP_RECORDING_CLICK"
    STOP_RECORDING_CALLBACK_ENTERED = "STOP_RECORDING_CALLBACK_ENTERED"
    EXTRACT_RECORDING_MOUSE_ENTER = "EXTRACT_RECORDING_MOUSE_ENTER"
    EXTRACT_RECORDING_CLICK = "EXTRACT_RECORDING_CLICK"
    EXTRACT_RECORDING_CALLBACK_ENTERED = "EXTRACT_RECORDING_CALLBACK_ENTERED"


@dataclass(frozen=True)
class EventMessage:
    event_type: UIEvent
    payload: dict[str, Any] = field(default_factory=dict)


Subscriber = Callable[[EventMessage], None]


class EventBus:
    def __init__(self) -> None:
        self._subscribers: dict[UIEvent, list[Subscriber]] = defaultdict(list)
        self._history: list[EventMessage] = []

    def subscribe(self, event_type: UIEvent, callback: Subscriber) -> Callable[[], None]:
        self._subscribers[event_type].append(callback)

        def unsubscribe() -> None:
            if callback in self._subscribers[event_type]:
                self._subscribers[event_type].remove(callback)

        return unsubscribe

    def publish(self, event_type: UIEvent, payload: dict[str, Any] | None = None) -> EventMessage:
        message = EventMessage(event_type=event_type, payload=dict(payload or {}))
        self._history.append(message)
        for callback in tuple(self._subscribers.get(event_type, ())):
            callback(message)
        return message

    def history(self) -> tuple[EventMessage, ...]:
        return tuple(self._history)
